---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argocd

patches:
  - path: applications/crds.yaml
  - path: applications/network.yaml
  - path: applications/secrets.yaml
  - path: applications/system.yaml
