---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Keep this version in step with the CRD ref
# ../../../crds/base/kustomization.yaml.
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 10.4.0
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
