---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications
  - argocd
  - blackbox-exporter
  - cert-manager
  - cilium
  - cloudflared
  - cnpg
  - external-dns
  - grafana
  - kgateway
  - kube-state-metrics
  - local-path-provisioner
  - metrics-server
  - node-exporter
  - ntfy
  - pyroscope
  - sops
  - victoria-logs
  - victoria-metrics
