---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kube-system.yaml
  - ip-pool.yaml
  - l2-announcement.yaml
  - gateway-parameters.yaml
  - gateways.yaml
  - cluster-issuer.yaml
  - certificates.yaml
  - hubble-route.yaml
