---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cloud Native Postgres operator manifest
  # See: https://cloudnative-pg.io/documentation/1.17/installation_upgrade/#directly-using-the-operator-manifest
  - https://raw.githubusercontent.com/cloudnative-pg/artifacts/release-1.30/manifests/operator-manifest.yaml
